Gamestate = require "hump.gamestate"

States = {}

States["menu"] = require "mainmenu"
States["lose"] = require "lose"
States["win"] = require "win"

States["level1"] = require "level1"
States["level2"] = require "level2"
States["level3"] = require "level3"
States["level4"] = require "level4"
States["level5"] = require "level5"
States["level6"] = require "level6"
States["level7"] = require "level7"
States["level8"] = require "level8"
States["level9"] = require "level9"

States["newstate1"] = require "newstate1"

States["level10"] = require "level10"
States["level11"] = require "level11"
States["level12"] = require "level12"
States["level13"] = require "level13"
States["level14"] = require "level14"
States["level15"] = require "level15"
States["level16"] = require "level16"
States["level17"] = require "level17"

States["newstate2"] = require "newstate2"

States["level18"] = require "level18"
States["level19"] = require "level19"
States["level20"] = require "level20"
States["level21"] = require "level21"
States["level22"] = require "level22"
States["level23"] = require "level23"

Images = {}
Sounds = {}

function love.load()
  love.window.setMode(1280,720)

  Font60 = love.graphics.newFont("resources/font.ttf", 60)
  Font45 = love.graphics.newFont("resources/font.ttf", 45)
  Font35 = love.graphics.newFont("resources/font.ttf", 35)

  Sounds["click"] = love.audio.newSource("resources/click.mp3", "static")

  Images["menu"] = love.graphics.newImage("resources/menu.png")
  Images["lose"] = love.graphics.newImage("resources/lose.png")
  Images["win"] = love.graphics.newImage("resources/win.png")
  Images["newstate"] = love.graphics.newImage("resources/newstate.png")

  Images["level1"] = love.graphics.newImage("resources/level1.png")
  Images["level2"] = love.graphics.newImage("resources/level2.png")
  Images["level3"] = love.graphics.newImage("resources/level3.png")
  Images["level4"] = love.graphics.newImage("resources/level4.png")
  Images["level5"] = love.graphics.newImage("resources/level5.png")
  Images["level6"] = love.graphics.newImage("resources/level6.png")
  Images["level7"] = love.graphics.newImage("resources/level7.png")
  Images["level8"] = love.graphics.newImage("resources/level8.png")
  Images["level9"] = love.graphics.newImage("resources/level9.png")
  
  Images["level10"] = love.graphics.newImage("resources/level10.png")
  Images["level11"] = love.graphics.newImage("resources/level11.png")
  Images["level12"] = love.graphics.newImage("resources/level12.png")
  Images["level13"] = love.graphics.newImage("resources/level13.png")
  Images["level14"] = love.graphics.newImage("resources/level14.png")
  Images["level15"] = love.graphics.newImage("resources/level15.png")
  Images["level16"] = love.graphics.newImage("resources/level16.png")
  Images["level17"] = love.graphics.newImage("resources/level17.png")
  
  Images["level18"] = love.graphics.newImage("resources/level18.png")
  Images["level19"] = love.graphics.newImage("resources/level19.png")
  Images["level20"] = love.graphics.newImage("resources/level20.png")
  Images["level21"] = love.graphics.newImage("resources/level21.png")
  Images["level22"] = love.graphics.newImage("resources/level22.png")
  Images["level23"] = love.graphics.newImage("resources/level23.png")

  Gamestate.registerEvents()
  Gamestate.switch(States["menu"])
end
