local state = {}

function state:enter()
  love.graphics.setBackgroundColor(0.9, 0.9, 0.9)
end

function state:draw()
  love.graphics.setColor(1, 1, 1)
  love.graphics.draw(Images["lose"], 640, 0)
  love.graphics.rectangle("fill", 100, 310, 440, 100)
  love.graphics.setColor(0, 0, 0)
  love.graphics.rectangle("line", 100, 310, 440, 100)
  love.graphics.setFont(Font60)
  love.graphics.print("Hävisit pelin!", 160, 330)
  love.graphics.setFont(Font35)
  love.graphics.print("Oi voi, ei noin voi toimia!", 150, 430)
end

function state:mousereleased(x, y, button, istouch, presses)
  Gamestate.switch(States["menu"])
end

return state
