local state = {}

function state:enter()
  love.graphics.setBackgroundColor(0.9, 0.9, 0.9)
end

function state:draw()
  love.graphics.setColor(0.8, 0.8, 0.8)
  love.graphics.rectangle("fill", 0, 480, 1280, 240)
  love.graphics.setColor(1, 1, 1)
  love.graphics.draw(Images["win"], 0, 0)
  love.graphics.rectangle("fill", 80, 405, 1120, 235)
  love.graphics.setColor(0, 0, 0)
  love.graphics.rectangle("line", 80, 405, 1120, 235)
  love.graphics.setFont(Font60)
  love.graphics.print("Onnittelut löysit tyttöystävän yhdessä", 150, 425)
  love.graphics.print("Johtaja98:n kanssa!", 380, 505)
  love.graphics.setFont(Font35)
  love.graphics.print("Mutta kuka tämä tyttöystävä on?.", 375,580)
end

function state:mousereleased(x, y, button, istouch, presses)
  Gamestate.switch(States["menu"])
end

return state
